# Generated by Django 4.1.7 on 2023-03-26 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Character Id')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Entry Id')),
                ('day_explanation', models.TextField(max_length=5000, verbose_name='Day Explanation')),
                ('over_all_sentiment_score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Over All Sentiment Score')),
                ('day_type', models.CharField(max_length=50, verbose_name='Day Type')),
                ('date', models.DateField(auto_now=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='User Id')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('email_id', models.EmailField(max_length=254, verbose_name='Email Id')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Occurence',
            fields=[
                ('occurence_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Occurence Id')),
                ('impact_type', models.CharField(max_length=50, verbose_name='Imapct Type')),
                ('sentiment_score', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Sentiment Score')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurences', to='myapp.character')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurences', to='myapp.entry')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='myapp.user'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='myapp.user'),
        ),
    ]
